### ISSUE TITLE
Building and fitting

### ISSUE THREAD

**Issue by kmcdermo** [trackreco/mkFit#123]
I wanted to open an issue until we decide what we want to do with building and fitting.  There are three distinct options:

1. Separate building and fitting routines (current situation)
2. Combined building and fitting routines (previous situation)
3. Another option: keep options for both (have building and fitting separate, and also have them together) --> would require careful logic and command line options

If we have b+f together in a single task (even as an option from an option from split), we would need to abstract the copy I/O to and from Matriplex data structures to and from the normal track vectors. This is because we would have to reuse the event_of_comb_candidates in a combined b+f, and this would overwrite the track parameters between building and fitting.  Since we wish to validate the track quality at each stage separately, we would have to have the copy in/out as part of the TBB task.

This is not the end of the world, as we can always enable the copy in/out a configurable that depends on if validation is being run or not.  For the timing benchmarks, we can decide if it is fair or not to exclude such a section from the time.

We discussed this a bit at the last meeting, Jan 26, so I will link the relevant slides here (flip to slide 8): https://indico.cern.ch/event/690884/contributions/2836372/attachments/1589129/2516956/BkFit_260118.pdf

@osschar @slava77 @dan131riley @cerati

**Comment by areinsvo** [comment]
This was done - fitting is now in MkBuilder/Finder. Closing this and opening other relevant issues.
