### ISSUE TITLE
What to do about Track

### ISSUE THREAD

**Issue by kmcdermo** [trackreco/mkFit#188]
As has been discussed for awhile (and most recently last Friday), there is some discussion on redoing the Track class, by splitting it into a base candidate class and a final candidate inherited class.

The base class would have minimal information passed around for mkFit building needs (parameters, covariance, score up to some amount of bits, last updated hit, etc), and at the very end of building, the final candidate would contain the rest (full list of hits, full chi2, other status objects, etc).

Granted, we may have a seismic shift coming soon in the form of a 5x5 block diagonal representation from our 6x6.

**Comment by areinsvo** [comment]
I think [Track Kaboom in PR 243](https://github.com/trackreco/mkFit/pull/243) effectively addressed this issue, so I'm going to go ahead and close this.
