### ISSUE TITLE
Recovering efficiency for short tracks

### ISSUE THREAD

**Issue by cerati** [trackreco/mkFit#195]
This issue is to track ideas to try to recover the efficiency for short tracks. Note that these are not monitored in the standard validation, see issue #193 to find the instructions to lower our selection.

- A first set of changes can be to change maxHolesPerCand from 12 to 3 and chi2Cut from 30 to 15 (as [already studied by Mario](https://docs.google.com/document/d/1WzGpClGtxHLgVmnpJqYysWXpof3RMRteusRTujeDza8/edit)). The effect can be seen in the plots [here](https://cerati.web.cern.ch/cerati/2018-12-07-test-short-tracks/) to [those posted by Kevin](https://kmcdermo.web.cern.ch/kmcdermo/mictrk/eff_comp_vs_nhits/75percent_allhits/simlayers5_recolayers5/). In particular it's interesting to see the effect on the efficiency vs pt ([new](https://cerati.web.cern.ch/cerati/2018-12-07-test-short-tracks/SIMVAL/SKL-SP_CMSSW_TTbar_PU70_eff_pt_zoom_build_pt0p0_SIMVAL.png), [old](https://kmcdermo.web.cern.ch/kmcdermo/mictrk/eff_comp_vs_nhits/75percent_allhits/simlayers5_recolayers5/SKL-SP_CMSSW_TTbar_PU70_eff_pt_zoom_build_pt0p0_SIMVAL.png)) and vs eta ([new](https://cerati.web.cern.ch/cerati/2018-12-07-test-short-tracks/SIMVAL/SKL-SP_CMSSW_TTbar_PU70_eff_eta_build_pt0p0_SIMVAL.png), [old](https://kmcdermo.web.cern.ch/kmcdermo/mictrk/eff_comp_vs_nhits/75percent_allhits/simlayers5_recolayers5/SKL-SP_CMSSW_TTbar_PU70_eff_eta_build_pt0p0_SIMVAL.png)). As expected, the fake rate also improves dramatically see e.g.: [new](https://cerati.web.cern.ch/cerati/2018-12-07-test-short-tracks/SIMVAL/SKL-SP_CMSSW_TTbar_PU70_fr_pt_zoom_build_pt0p0_SIMVAL.png) vs [old](https://kmcdermo.web.cern.ch/kmcdermo/mictrk/eff_comp_vs_nhits/75percent_allhits/simlayers5_recolayers5/SKL-SP_CMSSW_TTbar_PU70_fr_pt_zoom_build_pt0p0_SIMVAL.png).

- Another idea is to modify our candidate ranking. I think what we do is not correct for short tracks. If I understand correctly we compute the number of missing hits [here](https://github.com/cerati/mictest/blob/devel/Track.h#L559). But in this way we are counting all invalid hits, even those after the last valid hit. Instead we should count only the invalid hits 'inside' a track. @mmasciov, can you please take a look? You can probably just loop backwards and count invalid hits only after a first valid hit is found.

- We should review our parameters for the building keeping the short tracks in the metric plots: @mmasciov of course and also @areinsvo for the cluster charge cut, this is something you should take a look at...

- Placeholder for more ideas!

**Comment by kmcdermo** [comment]
This can now be safely closed, as PR #239 has been merged. Glad to see this one go.
