### ISSUE TITLE
migrating to gcc7

### ISSUE THREAD

**Issue by kmcdermo** [trackreco/mkFit#199]
In line with the discussion of today's discussion, and other issues like #174, #171 , #170 , the proposal is to move to gcc7 on phi1, phi2, phi3 and then update the Makefile + documentation accordingly. My only concern is that the proposal included grabbing devtoolset to get the latest gcc, which we have tried before and failed utterly to get a consistent icc/gcc/c++/ROOT version (see issue #149). 

The best would be to tell the initialization scripts to pick up a consistent ROOT/gcc setup. This would also tie us closer to CMSSW_10_X which sounds what was proposed today anyway to do.

**Comment by srlantz** [comment]
We leapfrogged gcc7 and went to gcc8 with PR #253. It updates init-env.sh to do pretty much what was recommended in this issue. And we're now aligned with the gcc currently favored by CMS-SW.
